[pytest]
python_files = test_*.py *_tests.py
python_functions = test_*
python_classes = Test*
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = True

markers =
    regression: Маркировка для регрессионных тестов.
    registration: Маркировка для тестов, связанных с регистрацией пользователей.
    authorization: Маркировка для тестов, связанных с авторизацией пользователей.
    courses: Маркировка для тестов, связанных с эндпоинтом ./courses